---
- hosts: localhost
  gather_facts: no
  tasks:
    - block:
      - name: get server url
        shell: oc whoami --show-server
        register: server_cmd
        failed_when: server_cmd.rc != 0

      - name: Login with integreatly-admin user
        shell: "oc login {{ server_cmd.stdout }} --username=integreatly-admin --password={{ hostvars['EVAL_VARS']['adminPassword'] }}"
        register: oc_login
        failed_when: oc_login.rc != 0 and '401 Unauthorized' not in oc_login.stdout
        # after a installation has been run successfully once, we will have no htpasswd auth anymore so need to login as the admin via rhsso
      - block:
          - name: get password for admin user
            script: "../../scripts/get_admin_secret.sh"
            register: admin_password
            failed_when: admin_password.rc != 0
          - name: login with admin user via rhsso identity provider when htpasswd disabled
            shell: "oc login {{ server_cmd.stdout }} --username=admin --password={{ admin_password.stdout }}"
        when: oc_login.rc != 0 and '401 Unauthorized' in oc_login.stdout and create_cluster_admin
      when: create_cluster_admin