---

- name: Create temp directory for doing work in on target
  become: true
  command: mktemp -td openshift-prometheus-ansible-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: Create templates subdirectory
  become: true
  file:
    state: directory
    path: "{{ tempdir }}/{{ item }}"
    mode: 0755
  changed_when: False
  with_items:
    - templates

- include_tasks: install_prometheus.yaml
  become: true
  when: openshift_prometheus_state == 'present'

- name: restart prometheus pod
  become: true
  shell: "oc delete pod prometheus-0 -n {{ openshift_prometheus_namespace }}"
  when: openshift_prometheus_state == 'present'

- include_tasks: uninstall_prometheus.yaml
  become: true
  when: openshift_prometheus_state == 'absent' or openshift_metrics_uninstall == true

- include_tasks: install_node_exporter.yaml
  become: true
  when: openshift_prometheus_node_exporter_install | default(true) | bool or openshift_metrics_uninstall == false

- name: Delete temp directory
  become: true
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False
