---
- hosts: managed
  gather_facts: no

- import_playbook: ../gather_cluster_facts.yml

- import_playbook: ../install.yml
  when: core_install | default(true) | bool

- import_playbook: ../backup_restore/install.yml
  when: backup_restore_install | default(true) | bool
