---
- hosts: master
  gather_facts: no
  tasks:
    - when: create_cluster_admin
      block:
        - name: remove integreatly-admin user
          shell: "htpasswd -D /etc/origin/master/htpasswd integreatly-admin"
          become: yes
        - name: make sure we start as system admin
          shell: oc login -u system:admin
          register: oc_login
          failed_when: oc_login.rc != 0
        - name: generate admin password
          set_fact:
            adminPass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
        - add_host:
            name: EVAL_VARS
            adminPassword: "{{adminPass}}"
        - name: Create integreatly-admin user
          shell: htpasswd -b /etc/origin/master/htpasswd integreatly-admin {{adminPass}}
          register: user_cmd
          failed_when: user_cmd.rc != 0
          become: true

        - name: Give integreatly-admin user cluster admin
          shell: oc adm policy add-cluster-role-to-user cluster-admin integreatly-admin
          register: oc_cmd
          failed_when: oc_cmd.rc != 0

    - include_role:
        name: webapp
        tasks_from: cors
      tags: ['webapp', 'remote']
      when: webapp

    - include_role:
        name: rhsso
        tasks_from: identityprovider
      vars:
        rhsso_openshift_master_config_path: "{{ eval_openshift_master_config_path }}"
      tags: ['rhsso', 'remote']
      when: webapp
